### ISSUE TITLE
cannot build app after upgrader 1.0.0 -> 1.0.1 

### ISSUE THREAD

**Issue by jirapatj** [ketanchoyal/custom_radio_grouped_button#15]
I upgrade version from 1.0.0 to 1.0.1 and i found error 
1. attribute "hight" rename to "height"
2. I cannot build apk file and got some exception from attach file

![messageImage_1593704631172](https://user-images.githubusercontent.com/7393333/86386216-a9afd300-bcbb-11ea-9127-2e13b4cd5e97.jpg)

How I can fix it?

**Comment by ketanchoyal** [comment]
Thanks for reporting, for now, you can use the previous version i.e 1.0.0 until this bug is resolved
