### ISSUE TITLE
it can't be centered

### ISSUE THREAD

**Issue by neutrin0x** [ketanchoyal/custom_radio_grouped_button#17]
first off thanks for this! it looks very nice!

When I put the widget inside a Column with it's mainAxisAlignment on center, everything is centered but the CustomRadioButton stays on left always.

**Comment by ketanchoyal** [comment]
@neutrin0x  Thanks for reporting, I'll soon update the package

**Comment by YouSour** [comment]
@ketanchoyal hi, how  can i  align to left or right ? i put it in column  crossAxisAlignment: CrossAxisAlignment.start , it doesn't work.
