### ISSUE TITLE
defaultSelected is broken

### ISSUE THREAD

**Issue by seanradford** [ketanchoyal/custom_radio_grouped_button#20]
In 1.0.3, creating a CustomRadioButton with a default selected does not work.

The initState method checks against the buttonValues and if a match is found then _currentSelected**Label** is set to the defaultSelected (value).

Then during button building the _currentSelectedLabel is checked against the list of button labels, which would only find a match if the labels and the values are the same.

I would have thought that changing to only look at button values is the correct thing, changing _currentSelectedLabel to _currentSelectedValue

Hope that makes sense. Thank you.

**Comment by ketanchoyal** [comment]
@seanradford  Thanks for reporting
