### ISSUE TITLE
Mirror enhances

### ISSUE THREAD

**Issue by bogdan-develop** [ketanchoyal/custom_radio_grouped_button#22]
![image](https://user-images.githubusercontent.com/61073510/89393760-d08b7a00-d73d-11ea-9389-364d064d120a.png)

- can't create like above, even `space = 0` and `padding = 0`
- can't apply custom text style
- `horizontal = true` is so ambiguous.
- labels can be duplicated, while values should be unique.

**Comment by ketanchoyal** [comment]
@bogdan-develop Thanks for reporting, I'll update it soon

**Comment by ketanchoyal** [comment]
a property 'absoluteZeroSpacing' is added to achieve something like above image, still, there will be some updates later this month which will make sure that above widget can be made accurately.

Custom text style can be applied now
Labels can be duplicated as requested
