### ISSUE TITLE
CustomCheckBoxGroup class defaultSelected

### ISSUE THREAD

**Issue by success-0627** [ketanchoyal/custom_radio_grouped_button#24]
Thank you for your great package.
`CustomCheckBoxGroup` would be used to be selected multiple options.
But `defaultSelected` field is not supporting `List`, but only an item.
Because `CustomRadioButton` will be used for single chose, `defaultSelected` should be single item.
Would you please kindly sort this problem out?
Best regards.

**Comment by ketanchoyal** [comment]
sure, will update it soon

**Comment by success-0627** [comment]
Hi @ketanchoyal , would you please take a look and merge ?
Thank you.
