### ISSUE TITLE
Border is rounded onSelect for Squared Shape

### ISSUE THREAD

**Issue by suhailpcv** [ketanchoyal/custom_radio_grouped_button#30]
![Screenshot 2020-09-22 at 9 39 09 PM](https://user-images.githubusercontent.com/60662024/93890267-bffa8780-fd1c-11ea-8a7a-42de50597598.png)
This happens to me. Do you know why? enableShape is false. I even removed it.

**Comment by suhailpcv** [comment]
hello, any update regarding this?

**Comment by suhailpcv** [comment]
hello, why is this issue ignored

**Comment by ketanchoyal** [comment]
Sorry @suhailpcv for the delayed reply, I'll update this package as soon as possible

**Comment by suhailpcv** [comment]
thanks @ketanchoyal ! I really like your library, hopefully you can fix this as soon as possible.

btw, something is weird about your checkBoxButtonValues. it's returning List<Object> instead of the type I use for the checkbox. for my case is String.

so I have to do this instead for it to work or else it wont update.
```
checkBoxButtonValues: (values) {
  var genderValue = values.map((gender) => gender.toString()).toList();
  vm.update(genderPreference: genderValue);
},
```

**Comment by ketanchoyal** [comment]
@suhailpcv this should be fixed now
