### ISSUE TITLE
"\n" not working in buttonLables text 

### ISSUE THREAD

**Issue by SangRyeol-Yun** [ketanchoyal/custom_radio_grouped_button#41]

**Comment by pishguy** [comment]
@SangRyeol-Yun 

i added this support

please see this link: https://github.com/ketanchoyal/custom_radio_grouped_button/pull/43

**Comment by ketanchoyal** [comment]
to enable multi-line support I have to rethink the logic to calculate height and several other things, your PR is looks good but it doesn’t consider all the cases, it breaks the UI
