### ISSUE TITLE
README improvement

### ISSUE THREAD

**Issue by Ascenio** [ketanchoyal/custom_radio_grouped_button#48]
Just a suggestion. I think the first thing a visitor wants to see is a preview of the package, and you have one, great. But, it's not at the top of the file, so chances are the user will left the repo before even looking at it.

**Comment by ketanchoyal** [comment]
Thanks for the suggestions but I already have screenshots attached to readme file

**Comment by Ascenio** [comment]
Yes, I know. What I meant was to put it at the top to be more visible.
