### ISSUE TITLE
Can't use scroll controller

### ISSUE THREAD

**Issue by YahyaYousef** [ketanchoyal/custom_radio_grouped_button#55]
**CustomRadioButton** did not include **scrollController** to handle scrolling programmatically
@ketanchoyal 
@omar-hanafy 
@patuoynageek 
@guissalustiano

**Comment by ketanchoyal** [comment]
This shouldn't be hard to add, never had any usecase until now, anyways I'll add this feature soon.

Thanks for using this package

**Comment by YahyaYousef** [comment]
@ketanchoyal 
The case was when using this package with windows in new flutter version
I cant scroll horizontally without scrollbar
please add this feature ASAP

**Comment by ketanchoyal** [comment]
@YahyaYousef sure I'll add it asap, or I'll appreciate it you can make a PR for it

Thanks
