### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by giantss** [ketanchoyal/custom_radio_grouped_button#71]
oh, i found a bug。

When the `horizontal` property is set to `false`, the `disabledValues` configuration item is invalid.

**Comment by ketanchoyal** [comment]
Please try again, there is no such bug and if you're able to reproduce it please add steps to reproduce with the code, 

make sure to use latest pub version

**Comment by giantss** [comment]
Thanks, it's no problem to upgrade to the latest version. The previous version was v2.1.8.
